### ISSUE TITLE
`kDISqThr` is ignored with runner

### ISSUE THREAD

**Issue by felixhekhorn** [NNPDF/yadism#167]
Because the compatibility update is always applied https://github.com/NNPDF/yadism/blob/e51117976afe1c69a0645d4dc5b97c7bad8a8017/src/yadism/runner.py#L91
this makes also this line always running https://github.com/NNPDF/yadism/blob/e51117976afe1c69a0645d4dc5b97c7bad8a8017/src/yadism/input/compatibility.py#L132-L134
and hence effectively `kDISqThr` is always ignored when using the runner (which is almost always the case)

**Comment by AleCandido** [comment]
I would not fix this, at least not with `kDISqThr`.

Instead, I'd recommend migrating to dataclasses, and restricting the runcards content to yadism specific options. The compatibility will be kept and updated, but only if the input is an old runcard.

Once we'll implement #166, there will be no need for any matching scale any longer, since the matching will be fully and only performed during PDF evolution (and not inside coeff funcs).

**Comment by giacomomagni** [comment]
This is now fixed, correct? @felixhekhorn.

**Comment by felixhekhorn** [comment]
yes, I think so - indeed, searching for `kDIS` yields no relevant match
