### ISSUE TITLE
Regression tests fail

### ISSUE THREAD

**Issue by Radonirinaunimi** [NNPDF/yadism#190]
Currently, the regression tests are failing because py3.7 is no longer supported and/or the `dev_requirements.txt` file no longer exists. So the question is whether we would like to skip these tests as is currently done in master (or to remove them completely) or fix them.

**Comment by felixhekhorn** [comment]
Just to say that I deactivated them in https://github.com/NNPDF/yadism/commit/cde006658a2c3daef7f59343242e72eabd40fa09 on master because they are hopelessly out dated (~2020), so I don't know whether we can rescue them ... I'd rather drop them all together and restart eventually (if ever we have time :upside_down_face: ) from scratch

**Comment by Radonirinaunimi** [comment]
Closing this issue as it is sort of (temporarily) addressed in master. This could be re-opened again when the fixing will start.
